"""
  Base class for which all other modules inherit from in the application.
  Abstract class, autogenerated by Ruby on Rails.
"""
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end
